# Generated by Django 5.2.6 on 2025-12-25 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url_Manager', '0002_rename_user_owner_section_user_owner_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls_by_section',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls_by_this_section', to='Url_Manager.section'),
        ),
    ]
