# Generated by Django 5.2.6 on 2026-01-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url_Manager', '0004_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls_by_section',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
