# Generated by Django 5.2.6 on 2025-11-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url_Manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='user_owner',
            new_name='user_owner_section',
        ),
        migrations.CreateModel(
            name='Urls_by_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('favicon', models.URLField(blank=True)),
                ('user_owner_urls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
