# Generated by Django 5.2.6 on 2026-01-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url_Manager', '0003_urls_by_section_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
